package CLI;

import Backend.BackingStore;
import Backend.Crypto;

import javax.crypto.SecretKey;
import java.io.Console;
import java.util.logging.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private final static Logger LOGGER = Logger.getLogger(App.class.getName());

    public static void main(String[] args) {
        if (!App.init()) {
            LOGGER.severe("Failed to initialise, exiting.");
            return;
        }


    }

    private static boolean init() {
        if (!Crypto.init()) {
            return false;
        }

        SecretKey masterKey = getMasterPassword();

        if (!BackingStore.init(masterKey)) {
            return false;
        }

        return true;
    }

    private static SecretKey getMasterPassword() {
        Console console = System.console();
        String password = new String(console.readPassword("Please enter master password: "));
        return Crypto.secretKeyFromBytes(password.getBytes());
    }
}
