/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import postit.client.backend.BackingStore;
import postit.client.cli.App;
import postit.client.cli.CLIKeyService;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        CLIKeyService keyService = new CLIKeyService();
        BackingStore backingStore = new BackingStore(keyService);
        App classUnderTest = new App(keyService, backingStore);
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
