/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import postit.client.backend.BackingStoreImpl;
import postit.client.cli.App;
import postit.client.cli.CLIKeyService;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        CLIKeyService keyService = new CLIKeyService();
        BackingStoreImpl backingStore = new BackingStoreImpl(keyService);
        App classUnderTest = new App(keyService, backingStore);
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
